### ISSUE TITLE
Model and weights

### ISSUE THREAD

**Issue by ethancohen123** [recursionpharma/maes_microscopy#2]
Are you planning to release the model (the big one ) weights with some inference code ?

**Comment by TernencezzZ** [comment]
need it too

**Comment by kian-kd** [comment]
We will not be releasing the large model (ViT-L/8+) weights at this time. However, we have partnered with Nvidia to host a smaller but more flexible version of the foundation model, which we call Phenom-Beta. It achieves about 0.56 recall on CORUM (better than ViT-L imagenet). Users can hit their API to get embeddings directly, which handles the auto-scaling and inference logic:

- https://blogs.nvidia.com/blog/drug-discovery-bionemo-generative-ai/
- https://www.youtube.com/watch?v=Gch6bX1toB0
